language: android
jdk: oraclejdk8
android:
  components:
            - platform-tools
            - tools
            - build-tools-29.0.3
            - android-29
           

sudo: true

before_install:
 - cd android
 - chmod +x  gradlew  
   
script:
    - gradlew assembleDebug  --stacktrace
notifications:
  email:
    - rodriguezlucasjavier1984@gmail.com
    - constanza.sanmartino@gmail.com
    - chiesapaula9@gmail.com 
    
