
language: android
jdk: oraclejdk8
android:
  components:
            - platform-tools
            - tools
            - build-tools-25.0.3
            - android-25
           

sudo: true

before_install:
 - chmod +x ./android/gradlew      
script:
    - ./android/gradlew assembleDebug   
notifications:
  email:
    - rodriguezlucasjavier1984@gmail.com
    - constanza.sanmartino@gmail.com
    - chiesapaula9@gmail.com 
    