#.travis.yml
language: node_js
node_js:
  - "12.16.2"

before_script:
  - npm install -g @angular/cli
  
script:
  - ng test --watch=false --browsers=ChromeHeadless
  - ng e2e --protractor-config='e2e/ci.protractor.conf.js'  
  - ng build --prod=false


deploy:
   provider: pages
   cleanup: true
   github_token: $GITHUB_TOKEN
   local_dir: www
   on:
    branch: master

notifications:
  email:
    -rodriguezlucasjavier1984@gmail.com
    -constanza.sanmartino@gmail.com
    -chiesapaula9@gmail.com 
    
  on_failure: change
  on_success: change