language: android
jdk: oraclejdk8
android:
  components:
            - platform-tools
            - tools
            - build-tools-29.0.3
            - android-29
           

sudo: true

before_install:
 - chmod +x ./android/gradlew  
 - TRAVIS_BUILD_DIR: /home/travis/build/constanzasanmartino/green-globe/android    
script:
    - ./gradlew assembleDebug  --stacktrace
notifications:
  email:
    - rodriguezlucasjavier1984@gmail.com
    - constanza.sanmartino@gmail.com
    - chiesapaula9@gmail.com 
    