#.travis.yml
language: node_js
node_js:
  - "12.16.2"

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  
script:
  - ng test --watch=false --browsers=ChromeHeadless --code-coverage --reporters=coverage-istanbul
  - ng e2e --protractor-config='e2e/ci.protractor.conf.js'  
  - ng build --prod=false

after_success:
  - firebase deploy --token $FIREBASE_TOKEN


notifications:
  email:
    -rodriguezlucasjavier1984@gmail.com
    -constanza.sanmartino@gmail.com
    -chiesapaula9@gmail.com 
    