language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3
  - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - tools
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"

install:
  - nvm install 12.16.2 
  - npm install 
  - npm install -g  @angular/cli

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

before_script:
  - chmod +x  ./android/gradlew 
     
script:
  - ng build --prod=false
  - npx cap copy
  - npx cap copy android
  - cd android
  - ./gradlew assembleDebug  --stacktrace

after_success:
  - ../firebase deploy --token $FIREBASE_TOKEN

before_deploy:
  - export APP_VERSION=$(./gradlew :app:printVersionName)

deploy:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file: ./app/build/outputs/apk/release/*
    file_glob: true
    skip_cleanup: true
    overwrite: true
    name: "$APP_VERSION"
    tag_name: "$APP_VERSION"
    on:
        branch: master

notifications:
  email:
    - rodriguezlucasjavier1984@gmail.com
    - constanza.sanmartino@gmail.com
    - chiesapaula9@gmail.com 
    
