#.travis.yml
language: node_js
node_js:
  - "12.16.2"
branches:
only:
  - master
before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
script:
  - ng link
  - ng test
  - ng e2e
  - ng build --prod=false
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
notifications:
  email:
  on_failure: change
  on_success: change