#.travis.yml
language: node_js
node_js:
  - "12.16.2"
addons:
chrome: stable
branches:
only:
  - master
before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
script:
  - ng test --watch=false --browsers=ChromeHeadless
  - ng e2e --protractor-config='e2e/ci.protractor.conf.js'  --webdriver-update false
  - ng build --prod=false
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
notifications:
  email:
  on_failure: change
  on_success: change